# Generated by Django 5.0.6 on 2024-06-15 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodotto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_di_partenza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('prodotto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asta', to='prodotto.prodotto')),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aste', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_offerta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orario_offerta', models.DateTimeField(auto_now_add=True)),
                ('asta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to='asta.asta')),
                ('profilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
