# Generated by Django 5.0.6 on 2024-06-20 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asta', '0002_recensione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='asta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='asta.asta'),
        ),
        migrations.AlterUniqueTogether(
            name='recensione',
            unique_together={('mittente', 'destinatario', 'asta')},
        ),
    ]
