# Generated by Django 5.0.6 on 2024-06-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.CharField(choices=[('ELETTRONICA', 'Elettronica'), ('ABBIGLIAMENTO', 'Abbigliamento'), ('CASA', 'Casa'), ('SPORT', 'Sport'), ('GIOCHI', 'Giochi'), ('LIBRI', 'Libri')], max_length=50),
        ),
    ]
