# Generated by Django 5.0.6 on 2024-06-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotto', '0002_alter_prodotto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='immagine',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
