# Generated by Django 5.0.6 on 2024-06-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotto', '0003_alter_prodotto_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='immagine',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
