# Generated by Django 5.0.6 on 2024-06-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotto', '0004_alter_prodotto_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
